Repository SOPT-all/35-COLLABORATION-SERVER-SAFETYREPORT, pull requests merged in 2024-11, with the labels that each got.

#2 [#1] feat: 프로젝트 초기 세팅
  .idea/.gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/safetyreport/safetyreport/SafetyreportApplication.java
  src/main/resources/application.properties
  src/test/java/com/safetyreport/safetyreport/SafetyreportApplicationTests.java
Labels: feat, 혜린

#8 [feat] #7 - 커스텀 응답 및 예외 처리, 프로젝트 세팅 수정, API 구현
  .gitignore
  .idea/.gitignore
  build.gradle
  src/main/java/com/safetyreport/SafetyreportApplication.java
  src/main/java/com/safetyreport/domain/api/ReportController.java
  src/main/java/com/safetyreport/domain/api/dto/response/CategoryDetail.java
  src/main/java/com/safetyreport/domain/api/dto/response/CategoryRetrieveResponse.java
  src/main/java/com/safetyreport/domain/api/dto/response/PhotoDetail.java
  src/main/java/com/safetyreport/domain/api/dto/response/PhotoRetrieveResponse.java
  src/main/java/com/safetyreport/domain/entity/BannerEntity.java
  src/main/java/com/safetyreport/domain/entity/CategoryEntity.java
  src/main/java/com/safetyreport/domain/entity/PhotoEntity.java
  src/main/java/com/safetyreport/domain/entity/ReportEntity.java
  src/main/java/com/safetyreport/domain/entity/UserEntity.java
  src/main/java/com/safetyreport/domain/entity/enums/CategoryEnum.java
  src/main/java/com/safetyreport/domain/mapper/BannerMapper.java
  src/main/java/com/safetyreport/domain/mapper/CategoryMapper.java
  src/main/java/com/safetyreport/domain/mapper/PhotoMapper.java
  src/main/java/com/safetyreport/domain/mapper/ReportMapper.java
  src/main/java/com/safetyreport/domain/mapper/UserMapper.java
  src/main/java/com/safetyreport/domain/repository/BannerRepository.java
  src/main/java/com/safetyreport/domain/repository/CategoryRepository.java
  src/main/java/com/safetyreport/domain/repository/PhotoRepository.java
  src/main/java/com/safetyreport/domain/repository/ReportRepository.java
  src/main/java/com/safetyreport/domain/repository/UserRepository.java
  src/main/java/com/safetyreport/domain/service/ReportService.java
  src/main/java/com/safetyreport/domain/service/domain/Banner.java
  src/main/java/com/safetyreport/domain/service/domain/Category.java
  src/main/java/com/safetyreport/domain/service/domain/Photo.java
  src/main/java/com/safetyreport/domain/service/domain/Report.java
  src/main/java/com/safetyreport/domain/service/domain/User.java
  src/main/java/com/safetyreport/global/config/JpaAuditingConfig.java
  src/main/java/com/safetyreport/global/entity/BaseTimeEntity.java
  src/main/java/com/safetyreport/global/exception/BusinessException.java
  src/main/java/com/safetyreport/global/exception/code/ErrorCode.java
  src/main/java/com/safetyreport/global/exception/code/SuccessCode.java
  src/main/java/com/safetyreport/global/exception/dto/ErrorResponse.java
  src/main/java/com/safetyreport/global/exception/dto/SuccessResponse.java
  src/main/java/com/safetyreport/global/handler/GlobalExceptionHandler.java
  src/main/resources/application.properties
  src/test/java/com/safetyreport/SafetyreportApplicationTests.java
Labels: feat, 혜린

#6 [#5]feat: 홈화면 GET api구현
  build.gradle
  src/main/java/com/safetyreport/domain/api/HomeController.java
  src/main/java/com/safetyreport/domain/api/ReportController.java
  src/main/java/com/safetyreport/domain/api/dto/request/PostReportRequest.java
  src/main/java/com/safetyreport/domain/api/dto/response/BannerDetail.java
  src/main/java/com/safetyreport/domain/api/dto/response/CreateRetrieveResponse.java
  src/main/java/com/safetyreport/domain/api/dto/response/HomeRetrieveResponse.java
  src/main/java/com/safetyreport/domain/entity/PhotoEntity.java
  src/main/java/com/safetyreport/domain/entity/ReportEntity.java
  src/main/java/com/safetyreport/domain/mapper/PhotoMapper.java
  src/main/java/com/safetyreport/domain/mapper/ReportMapper.java
  src/main/java/com/safetyreport/domain/repository/PhotoRepository.java
  src/main/java/com/safetyreport/domain/repository/ReportRepository.java
  src/main/java/com/safetyreport/domain/service/HomeService.java
  src/main/java/com/safetyreport/domain/service/ReportService.java
  src/main/java/com/safetyreport/domain/service/domain/Report.java
Labels: feat, 재민

#10 [chore] #9 - 코드 포맷팅 적용 및 url 변경
  src/main/java/com/safetyreport/domain/api/HomeController.java
  src/main/java/com/safetyreport/domain/api/ReportController.java
  src/main/java/com/safetyreport/domain/api/dto/request/PostReportRequest.java
  src/main/java/com/safetyreport/domain/api/dto/response/BannerDetail.java
  src/main/java/com/safetyreport/domain/api/dto/response/CreateRetrieveResponse.java
  src/main/java/com/safetyreport/domain/api/dto/response/HomeRetrieveResponse.java
  src/main/java/com/safetyreport/domain/entity/BannerEntity.java
  src/main/java/com/safetyreport/domain/entity/CategoryEntity.java
  src/main/java/com/safetyreport/domain/entity/PhotoEntity.java
  src/main/java/com/safetyreport/domain/entity/ReportEntity.java
  src/main/java/com/safetyreport/domain/entity/UserEntity.java
  src/main/java/com/safetyreport/domain/entity/enums/CategoryEnum.java
  src/main/java/com/safetyreport/domain/repository/BannerRepository.java
  src/main/java/com/safetyreport/domain/repository/PhotoRepository.java
  src/main/java/com/safetyreport/domain/repository/ReportRepository.java
  src/main/java/com/safetyreport/domain/service/HomeService.java
  src/main/java/com/safetyreport/domain/service/ReportService.java
  src/main/java/com/safetyreport/domain/service/domain/Report.java
Labels: 혜린, chore

#11 [deploy] main에 merge
  .gitignore
  .idea/.gitignore
  build.gradle
  src/main/java/com/safetyreport/SafetyreportApplication.java
  src/main/java/com/safetyreport/domain/api/HomeController.java
  src/main/java/com/safetyreport/domain/api/ReportController.java
  src/main/java/com/safetyreport/domain/api/dto/request/PostReportRequest.java
  src/main/java/com/safetyreport/domain/api/dto/response/BannerDetail.java
  src/main/java/com/safetyreport/domain/api/dto/response/CategoryDetail.java
  src/main/java/com/safetyreport/domain/api/dto/response/CategoryRetrieveResponse.java
  src/main/java/com/safetyreport/domain/api/dto/response/CreateRetrieveResponse.java
  src/main/java/com/safetyreport/domain/api/dto/response/HomeRetrieveResponse.java
  src/main/java/com/safetyreport/domain/api/dto/response/PhotoDetail.java
  src/main/java/com/safetyreport/domain/api/dto/response/PhotoRetrieveResponse.java
  src/main/java/com/safetyreport/domain/entity/BannerEntity.java
  src/main/java/com/safetyreport/domain/entity/CategoryEntity.java
  src/main/java/com/safetyreport/domain/entity/PhotoEntity.java
  src/main/java/com/safetyreport/domain/entity/ReportEntity.java
  src/main/java/com/safetyreport/domain/entity/UserEntity.java
  src/main/java/com/safetyreport/domain/entity/enums/CategoryEnum.java
  src/main/java/com/safetyreport/domain/mapper/BannerMapper.java
  src/main/java/com/safetyreport/domain/mapper/CategoryMapper.java
  src/main/java/com/safetyreport/domain/mapper/PhotoMapper.java
  src/main/java/com/safetyreport/domain/mapper/ReportMapper.java
  src/main/java/com/safetyreport/domain/mapper/UserMapper.java
  src/main/java/com/safetyreport/domain/repository/BannerRepository.java
  src/main/java/com/safetyreport/domain/repository/CategoryRepository.java
  src/main/java/com/safetyreport/domain/repository/PhotoRepository.java
  src/main/java/com/safetyreport/domain/repository/ReportRepository.java
  src/main/java/com/safetyreport/domain/repository/UserRepository.java
  src/main/java/com/safetyreport/domain/service/HomeService.java
  src/main/java/com/safetyreport/domain/service/ReportService.java
  src/main/java/com/safetyreport/domain/service/domain/Banner.java
  src/main/java/com/safetyreport/domain/service/domain/Category.java
  src/main/java/com/safetyreport/domain/service/domain/Photo.java
  src/main/java/com/safetyreport/domain/service/domain/Report.java
  src/main/java/com/safetyreport/domain/service/domain/User.java
  src/main/java/com/safetyreport/global/config/JpaAuditingConfig.java
  src/main/java/com/safetyreport/global/entity/BaseTimeEntity.java
  src/main/java/com/safetyreport/global/exception/BusinessException.java
  src/main/java/com/safetyreport/global/exception/code/ErrorCode.java
  src/main/java/com/safetyreport/global/exception/code/SuccessCode.java
  src/main/java/com/safetyreport/global/exception/dto/ErrorResponse.java
  src/main/java/com/safetyreport/global/exception/dto/SuccessResponse.java
  src/main/java/com/safetyreport/global/handler/GlobalExceptionHandler.java
  src/main/resources/application.properties
  src/test/java/com/safetyreport/SafetyreportApplicationTests.java
Labels: 혜린, deploy
